### ISSUE TITLE
CODE_OF_CONDUCT.md file missing

### ISSUE THREAD

**Issue by ghost** [mozilla/ca-policy#7]
As of January 1 2019, Mozilla requires that all GitHub projects include this [CODE_OF_CONDUCT.md](https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md) file in the project root. The file has two parts:

1. Required Text - All text under the headings *Community Participation Guidelines and How to Report*, are required, and should not be altered.
2. Optional Text - The Project Specific Etiquette heading provides a space to speak more specifically about ways people can work effectively and inclusively together. Some examples of those can be found on the [Firefox Debugger](https://github.com/devtools-html/debugger.html/blob/master/CODE_OF_CONDUCT.md) project, and [Common Voice](https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md). (The optional part is commented out in the [raw template file](https://raw.githubusercontent.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md), and will not be visible until you modify and uncomment that part.)

If you have any questions about this file, or Code of Conduct policies and procedures, please see [Mozilla-GitHub-Standards](https://wiki.mozilla.org/GitHub/Repository_Requirements) or email Mozilla-GitHub-Standards+CoC@mozilla.com.

_(Message COC001)_

**Comment by floatingatoll** [comment]
@WilsonKathleen Is this repository still in use, or was it later replaced by mozilla/pkipolicy?

**Comment by WilsonKathleen** [comment]
Correct. This mozilla/ca-policy repository was replaced by mozilla/pkipolicy.

**Comment by floatingatoll** [comment]
Ah, excellent. If you'd like to edit the Repo Description to indicate as much and then mark this repo as Archived under the Repo Settings, that would address this request and prevent future compliance checks against this deprecated repo. Mozilla's GitHub team can help with any/all of those steps, including granting you the access necessary to do so if you require it.

**Comment by wthayer** [comment]
@floatingatoll neither Kathleen or I have admin on this repo. Are you able to grant it to me so that I can make the requested changes?

**Comment by floatingatoll** [comment]
I contacted the admins in IRC/#github and asked them to step in here to
assist y’all (as I’m not one myself).

**Comment by hwine** [comment]
I'll merge & archive

**Comment by ghost** [comment]
@WilsonKathleen @wthayer fyi, I'm also taking down the site at http://mozilla.github.io/ca-policy/ so folks don't stumble on it.
